# Generated by Django 5.0.1 on 2024-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsimage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='social_image',
            new_name='news_image',
        ),
    ]
