# Generated by Django 5.0.1 on 2024-01-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingimage',
            name='description',
        ),
    ]
