# Generated by Django 5.0.1 on 2024-02-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_social_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about_image', models.FileField(upload_to='landing/static/landing/img/about')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
