# Generated by Django 5.0.1 on 2024-02-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_about_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_item',
            name='text',
            field=models.TextField(default='DESC'),
            preserve_default=False,
        ),
    ]
