# Generated by Django 4.2.5 on 2024-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_rename_text_about_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_item',
            name='link',
            field=models.CharField(default='www.youtube.com', max_length=255),
            preserve_default=False,
        ),
    ]
